# SELECT ROUND(AVG(FI.LENGTH_WITHOUT_NULL), 2) AS AVERAGE_LENGTH
# FROM (
#     SELECT *, IFNULL(LENGTH, 10) AS LENGTH_WITHOUT_NULL
#     FROM FISH_INFO
# ) AS FI;


SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AVERAGE_LENGTH
FROM FISH_INFO