# -- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, 
    ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D 
    ON D.CAR_TYPE = C.CAR_TYPE AND D.DURATION_TYPE = "30일 이상"
WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
    )
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC
