SELECT ID, 
CASE 
    WHEN SIZE.PERCENT <= 0.25 THEN 'CRITICAL'
    WHEN SIZE.PERCENT <= 0.5 THEN 'HIGH'
    WHEN SIZE.PERCENT <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PERCENT
    FROM ECOLI_DATA
) AS SIZE
ORDER BY ID; 
