-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, 
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소', 
    CONCAT(LEFT(U.TLNO, 3), '-', SUBSTRING(U.TLNO, 4, 4), '-', RIGHT(U.TLNO, 4)) AS '전화번호' 
FROM USED_GOODS_USER AS U
JOIN (
    SELECT COUNT(BOARD_ID) AS BOARD_COUNT, WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) AS UB ON UB.WRITER_ID = U.USER_ID
WHERE UB.BOARD_COUNT >= 3
ORDER BY U.USER_ID DESC