-- 코드를 입력하세요
SELECT *,
CASE 
    -- 당일 대여/반납을 1일로 치기 위해 +1 필수 
    WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '장기 대여'
    ELSE '단기 대여' 
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) = 9 
ORDER BY HISTORY_ID DESC