-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DUR), 1) AS AVERAGE_DURATION
FROM (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DUR
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS CH
GROUP BY CAR_ID
HAVING AVG(DUR) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
