SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY 
    GROUP BY(FLAVOR)
) AS J ON J.FLAVOR = F.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL) DESC
LIMIT 3
