-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS(
    SELECT 9 AS HOUR
    UNION ALL 
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 19
)

SELECT T.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIME_TABLE AS T
LEFT JOIN ANIMAL_OUTS AS A ON T.HOUR = HOUR(A.DATETIME) 
GROUP BY T.HOUR
ORDER BY T.HOUR


