-- 코드를 작성해주세요

# SELECT I.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY 
# FROM (
#     SELECT T.ITEM_ID
#     FROM ITEM_TREE AS T 
#     JOIN ITEM_INFO AS I ON I.ITEM_ID = T.PARENT_ITEM_ID
#     WHERE I.RARITY = "RARE" AND T.PARENT_ITEM_ID IS NOT NULL) AS I
# JOIN ITEM_INFO AS INFO ON I.ITEM_ID = INFO.ITEM_ID
# ORDER BY ITEM_ID DESC;

SELECT ITEM_ID, ITEM_NAME, RARITY 
FROM ITEM_INFO 
WHERE ITEM_ID IN (
    SELECT T.ITEM_ID
    FROM ITEM_TREE AS T 
    JOIN ITEM_INFO AS I ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE I.RARITY = "RARE" AND T.PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC;