-- 코드를 작성해주세요

-- 연도별 대장균 크기 중 가장 큰 것 
# select MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
# from ECOLI_DATA
# group by YEAR(DIFFERENTIATION_DATE);

# SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
# FROM ECOLI_DATA AS E 
# JOIN (
#     select MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
#     from ECOLI_DATA
#     group by YEAR(DIFFERENTIATION_DATE)
# ) AS M
# ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
# ORDER BY YEAR, YEAR_DEV; 

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, 
    ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV; 