# SELECT CONCAT('/home/grep/src/', UB.BOARD_ID, '/', UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) AS FILE_PATH
# FROM USED_GOODS_FILE AS UF 
# JOIN USED_GOODS_BOARD AS UB ON UB.BOARD_ID = UF.BOARD_ID
# WHERE (
#     SELECT MAX(VIEWS)
#     FROM USED_GOODS_BOARD 
# ) = UB.VIEWS
# ORDER BY UF.FILE_ID DESC


SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM (
    SELECT *, ROW_NUMBER() OVER (ORDER BY VIEWS DESC) AS RN FROM USED_GOODS_BOARD
) AS B
JOIN USED_GOODS_FILE AS F ON B.BOARD_ID = F.BOARD_ID
WHERE B.RN = 1
ORDER BY F.FILE_ID DESC